server {
    # Cloud Run injects the PORT dynamically, but defaults to 8080
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Fallback routing for SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}