steps:
  - name: "gcr.io/cloud-builders/mvn"
    args: ["-f", "backend/app/pom.xml", "clean", "package", "-DskipTests"]

serviceAccount: "projects/project-25c8d146-3e11-498c-a31/serviceAccounts/160316735954-compute@developer.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
