steps:
  # Step 1: Build the Docker image from the nested backend folder
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/googleriser-backend:$COMMIT_SHA",
        "backend/app",
      ]

  # Step 2: Push the image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/googleriser-backend:$COMMIT_SHA"]

  # Step 3: Deploy the new image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "googleriser-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/googleriser-backend:$COMMIT_SHA"
      - "--region"
      - "asia-southeast1"

# Ensure Cloud Build tracks the built image
images:
  - "gcr.io/$PROJECT_ID/googleriser-backend:$COMMIT_SHA"

serviceAccount: "projects/project-25c8d146-3e11-498c-a31/serviceAccounts/160316735954-compute@developer.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
